"""Initial migration

Revision ID: 58649ecdffa9
Revises: 
Create Date: 2026-01-07 23:53:36.013736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58649ecdffa9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('balance', sa.Double(), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('credit_debt', sa.Double(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Transaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payer_id', sa.Integer(), nullable=False),
    sa.Column('payee_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Double(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('balance_used', sa.Double(), nullable=False),
    sa.Column('credit_used', sa.Double(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payee_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Feed',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feed_type', sa.String(length=15), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('payer_id', sa.Integer(), nullable=True),
    sa.Column('payee_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payee_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['Transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Feed')
    op.drop_table('Transaction')
    op.drop_table('User')
    # ### end Alembic commands ###
